-- SwiftPay V2 A1 real-runtime acceptance fixture.
-- TEST ONLY. The plaintext Secret Key is generated by the acceptance harness and
-- never enters this file or PostgreSQL; only the supplied scrypt verifier does.

begin;

insert into app.merchants (
    id,
    name,
    lifecycle_status
) values
    (
        '60000000-0000-0000-0000-000000000001'::uuid,
        'A1 Runtime Active Merchant',
        'active'
    ),
    (
        '60000000-0000-0000-0000-000000000002'::uuid,
        'A1 Runtime Suspended Merchant',
        'suspended'
    )
on conflict (id) do update set
    name = excluded.name,
    lifecycle_status = excluded.lifecycle_status,
    suspended_at = case when excluded.lifecycle_status = 'suspended' then now() else null end,
    closed_at = null,
    updated_at = now();

insert into app.api_credentials (
    id,
    merchant_id,
    environment,
    name,
    public_key,
    secret_verifier,
    secret_version,
    status,
    ip_allowlist,
    last_used_at,
    rotated_at,
    revoked_at
) values
    (
        '61000000-0000-0000-0000-000000000001'::uuid,
        '60000000-0000-0000-0000-000000000001'::uuid,
        'sandbox',
        'A1 Runtime Active',
        'pk_a1_runtime_active',
        :'a1_secret_verifier',
        3,
        'active',
        '["127.0.0.1"]'::jsonb,
        null,
        null,
        null
    ),
    (
        '61000000-0000-0000-0000-000000000002'::uuid,
        '60000000-0000-0000-0000-000000000001'::uuid,
        'sandbox',
        'A1 Runtime IP Denied',
        'pk_a1_runtime_ip_denied',
        :'a1_secret_verifier',
        3,
        'active',
        '["192.0.2.10"]'::jsonb,
        null,
        null,
        null
    ),
    (
        '61000000-0000-0000-0000-000000000003'::uuid,
        '60000000-0000-0000-0000-000000000001'::uuid,
        'sandbox',
        'A1 Runtime Revoked',
        'pk_a1_runtime_revoked',
        :'a1_secret_verifier',
        2,
        'revoked',
        null,
        null,
        null,
        now()
    ),
    (
        '61000000-0000-0000-0000-000000000004'::uuid,
        '60000000-0000-0000-0000-000000000002'::uuid,
        'sandbox',
        'A1 Runtime Inactive Merchant',
        'pk_a1_runtime_inactive_merchant',
        :'a1_secret_verifier',
        5,
        'active',
        '[]'::jsonb,
        null,
        null,
        null
    )
on conflict (id) do update set
    merchant_id = excluded.merchant_id,
    environment = excluded.environment,
    name = excluded.name,
    public_key = excluded.public_key,
    secret_verifier = excluded.secret_verifier,
    secret_version = excluded.secret_version,
    status = excluded.status,
    ip_allowlist = excluded.ip_allowlist,
    last_used_at = null,
    rotated_at = excluded.rotated_at,
    revoked_at = excluded.revoked_at;

delete from app.api_credential_token_windows
where credential_id in (
    '61000000-0000-0000-0000-000000000001'::uuid,
    '61000000-0000-0000-0000-000000000002'::uuid,
    '61000000-0000-0000-0000-000000000003'::uuid,
    '61000000-0000-0000-0000-000000000004'::uuid
);

commit;
