-- SwiftPay V2 A2 real-runtime acceptance fixture.
-- TEST ONLY. The plaintext Secret Key is generated by the acceptance harness and
-- never enters this file or PostgreSQL; only the supplied scrypt verifier does.
-- This fixture is intentionally separate from K5 and A1.

begin;

insert into app.merchants (
    id,
    name,
    lifecycle_status
) values
    (
        '63000000-0000-0000-0000-000000000001'::uuid,
        'A2 Runtime Owner Merchant',
        'active'
    ),
    (
        '63000000-0000-0000-0000-000000000002'::uuid,
        'A2 Runtime Foreign Merchant',
        'active'
    )
on conflict (id) do update set
    name = excluded.name,
    lifecycle_status = 'active',
    suspended_at = null,
    closed_at = null,
    updated_at = now();

insert into app.api_credentials (
    id,
    merchant_id,
    environment,
    name,
    public_key,
    secret_verifier,
    secret_version,
    status,
    ip_allowlist,
    last_used_at,
    rotated_at,
    revoked_at
) values
    (
        '64000000-0000-0000-0000-000000000001'::uuid,
        '63000000-0000-0000-0000-000000000001'::uuid,
        'sandbox',
        'A2 Runtime Owner Sandbox',
        'pk_a2_runtime_owner',
        :'a2_secret_verifier',
        1,
        'active',
        '["127.0.0.1"]'::jsonb,
        null,
        null,
        null
    ),
    (
        '64000000-0000-0000-0000-000000000002'::uuid,
        '63000000-0000-0000-0000-000000000002'::uuid,
        'sandbox',
        'A2 Runtime Foreign Sandbox',
        'pk_a2_runtime_foreign',
        :'a2_secret_verifier',
        1,
        'active',
        '["127.0.0.1"]'::jsonb,
        null,
        null,
        null
    ),
    (
        '64000000-0000-0000-0000-000000000003'::uuid,
        '63000000-0000-0000-0000-000000000001'::uuid,
        'production',
        'A2 Runtime Owner Production',
        'pk_a2_runtime_production',
        :'a2_secret_verifier',
        1,
        'active',
        '["127.0.0.1"]'::jsonb,
        null,
        null,
        null
    )
on conflict (id) do update set
    merchant_id = excluded.merchant_id,
    environment = excluded.environment,
    name = excluded.name,
    public_key = excluded.public_key,
    secret_verifier = excluded.secret_verifier,
    secret_version = excluded.secret_version,
    status = 'active',
    ip_allowlist = excluded.ip_allowlist,
    last_used_at = null,
    rotated_at = null,
    revoked_at = null;

delete from app.api_credential_token_windows
where credential_id in (
    '64000000-0000-0000-0000-000000000001'::uuid,
    '64000000-0000-0000-0000-000000000002'::uuid,
    '64000000-0000-0000-0000-000000000003'::uuid
);

insert into app.providers (
    id,
    code,
    name,
    status
) values (
    '65000000-0000-0000-0000-000000000001'::uuid,
    'swiftpay_emulator',
    'SwiftPay Deterministic Emulator',
    'active'
)
on conflict (id) do update set
    code = excluded.code,
    name = excluded.name,
    status = 'active';

insert into app.provider_accounts (
    id,
    provider_id,
    merchant_id,
    name,
    environment,
    status,
    credentials_ciphertext,
    capabilities,
    configuration
) values (
    '66000000-0000-0000-0000-000000000001'::uuid,
    '65000000-0000-0000-0000-000000000001'::uuid,
    null,
    'A2 Sandbox Emulator Platform Account',
    'sandbox',
    'active',
    '{}'::jsonb,
    '{"create_pix_charge":true}'::jsonb,
    '{"mode":"emulator"}'::jsonb
)
on conflict (id) do update set
    provider_id = excluded.provider_id,
    merchant_id = null,
    name = excluded.name,
    environment = 'sandbox',
    status = 'active',
    credentials_ciphertext = '{}'::jsonb,
    capabilities = '{"create_pix_charge":true}'::jsonb,
    configuration = '{"mode":"emulator"}'::jsonb,
    updated_at = now();

commit;
