-- SwiftPay V2 A3 real-runtime acceptance fixture.
-- TEST ONLY. The plaintext API Secret Key is generated by the acceptance harness;
-- only the supplied scrypt verifier is persisted. This fixture is separate from
-- K5 and from the A2 runtime fixture.

begin;

insert into app.merchants (id, name, lifecycle_status) values
  ('73000000-0000-0000-0000-000000000001'::uuid, 'A3 Runtime Owner Merchant', 'active'),
  ('73000000-0000-0000-0000-000000000002'::uuid, 'A3 Runtime Foreign Merchant', 'active')
on conflict (id) do update set
  name = excluded.name,
  lifecycle_status = 'active',
  suspended_at = null,
  closed_at = null,
  updated_at = now();

insert into app.api_credentials (
  id, merchant_id, environment, name, public_key, secret_verifier,
  secret_version, status, ip_allowlist, last_used_at, rotated_at, revoked_at
) values
  (
    '74000000-0000-0000-0000-000000000001'::uuid,
    '73000000-0000-0000-0000-000000000001'::uuid,
    'sandbox', 'A3 Runtime Owner Sandbox', 'pk_a3_runtime_owner',
    :'a3_secret_verifier', 1, 'active', '["127.0.0.1"]'::jsonb,
    null, null, null
  ),
  (
    '74000000-0000-0000-0000-000000000002'::uuid,
    '73000000-0000-0000-0000-000000000002'::uuid,
    'sandbox', 'A3 Runtime Foreign Sandbox', 'pk_a3_runtime_foreign',
    :'a3_secret_verifier', 1, 'active', '["127.0.0.1"]'::jsonb,
    null, null, null
  ),
  (
    '74000000-0000-0000-0000-000000000003'::uuid,
    '73000000-0000-0000-0000-000000000001'::uuid,
    'production', 'A3 Runtime Owner Production', 'pk_a3_runtime_production',
    :'a3_secret_verifier', 1, 'active', '["127.0.0.1"]'::jsonb,
    null, null, null
  )
on conflict (id) do update set
  merchant_id = excluded.merchant_id,
  environment = excluded.environment,
  name = excluded.name,
  public_key = excluded.public_key,
  secret_verifier = excluded.secret_verifier,
  secret_version = 1,
  status = 'active',
  ip_allowlist = excluded.ip_allowlist,
  last_used_at = null,
  rotated_at = null,
  revoked_at = null;

delete from app.api_credential_token_windows
where credential_id in (
  '74000000-0000-0000-0000-000000000001'::uuid,
  '74000000-0000-0000-0000-000000000002'::uuid,
  '74000000-0000-0000-0000-000000000003'::uuid
);

-- Reuse the same deterministic emulator identity that A2 owns. Reasserting it
-- here makes this fixture independently runnable after migrations on a clean DB.
insert into app.providers (id, code, name, status) values (
  '65000000-0000-0000-0000-000000000001'::uuid,
  'swiftpay_emulator',
  'SwiftPay Deterministic Emulator',
  'active'
)
on conflict (id) do update set
  code = excluded.code,
  name = excluded.name,
  status = 'active';

insert into app.provider_accounts (
  id, provider_id, merchant_id, name, environment, status,
  credentials_ciphertext, capabilities, configuration
) values (
  '66000000-0000-0000-0000-000000000001'::uuid,
  '65000000-0000-0000-0000-000000000001'::uuid,
  null,
  'A3 Sandbox Emulator Platform Account',
  'sandbox',
  'active',
  '{}'::jsonb,
  '{"create_pix_charge":true}'::jsonb,
  '{"mode":"emulator"}'::jsonb
)
on conflict (id) do update set
  provider_id = excluded.provider_id,
  merchant_id = null,
  name = excluded.name,
  environment = 'sandbox',
  status = 'active',
  credentials_ciphertext = '{}'::jsonb,
  capabilities = '{"create_pix_charge":true}'::jsonb,
  configuration = '{"mode":"emulator"}'::jsonb,
  updated_at = now();

insert into app.webhook_endpoints (
  id, merchant_id, environment, url, status, secret_ciphertext,
  secret_version, previous_secret_ciphertext, previous_secret_version,
  previous_secret_expires_at, subscribed_events
) values (
  '77000000-0000-0000-0000-000000000001'::uuid,
  '73000000-0000-0000-0000-000000000001'::uuid,
  'sandbox',
  'https://a3-runtime.example.invalid/swiftpay',
  'active',
  'test-only-a3-webhook-ciphertext',
  1,
  null,
  null,
  null,
  '["payment.paid"]'::jsonb
)
on conflict (id) do update set
  merchant_id = excluded.merchant_id,
  environment = 'sandbox',
  url = excluded.url,
  status = 'active',
  secret_ciphertext = excluded.secret_ciphertext,
  secret_version = 1,
  previous_secret_ciphertext = null,
  previous_secret_version = null,
  previous_secret_expires_at = null,
  subscribed_events = '["payment.paid"]'::jsonb,
  updated_at = now();

commit;
