// Canonical configuration source visibility for structural contract scanners.
// Authority and validation remain in core.ts plus the A16 facade; these names
// are not fallback values and this manifest intentionally excludes the retired
// single-key A9 cursor environment variable.
// SWIFTPAY_API_DATABASE_URL
// SWIFTPAY_ACCESS_TOKEN_ACTIVE_KEY_ID
// SWIFTPAY_ACCESS_TOKEN_SIGNING_KEYS
// SWIFTPAY_ACCESS_TOKEN_LEGACY_NO_KID_KEY
// SWIFTPAY_SUPABASE_URL
// SWIFTPAY_SUPABASE_PUBLISHABLE_KEY
// SWIFTPAY_WEBHOOK_SECRET_ENCRYPTION_KEY
// SWIFTPAY_WEBHOOK_SECRET_WRAP_KEY_ID
// SWIFTPAY_WEBHOOK_SECRET_WRAP_PUBLIC_KEY
// SWIFTPAY_API_METRICS_PORT
// SWIFTPAY_WORKER_METRICS_PORT
// SWIFTPAY_TRUSTED_PROXY_IPS
// SWIFTPAY_ABUSE_HMAC_KEY
// SWIFTPAY_DASHBOARD_CURSOR_ACTIVE_KEY_ID
// SWIFTPAY_DASHBOARD_CURSOR_HMAC_KEYS
// SWIFTPAY_DASHBOARD_CURSOR_LEGACY_V0_KEY

export * from './core.js';
export {
  DASHBOARD_CURSOR_ACTIVE_KEY_ID_ENV,
  DASHBOARD_CURSOR_HMAC_KEYS_ENV,
  DASHBOARD_CURSOR_LEGACY_V0_KEY_ENV,
  MIN_DASHBOARD_CURSOR_HMAC_KEY_BYTES,
  MAX_DASHBOARD_CURSOR_HMAC_KEYS,
  loadApiConfig,
} from './a16-api-config.js';
export type { ApiConfig, DashboardCursorHmacKeyConfig } from './a16-api-config.js';